services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
     - './octoprint:/octoprint'
     - /dev/serial/by-id:/dev/serial/by-id
    device_cgroup_rules:
      - 'c 188:* rmw'
      - 'c 166:* rmw'
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    environment:
      TZ: "America/Phoenix"
    #  - ENABLE_MJPG_STREAMER=true

  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - PGID=0
  #    - TZ=America/Phoenix
  #  volumes:
  #    - octoprint:/octoprint

volumes:
  octoprint:
